export const cybersecurity = {
  gitHubLinks: [
    { name: "OWASP ZAP", url: "https://github.com/zaproxy/zap-core-help", description: "An open-source security tool" },
    { name: "Metasploit", url: "https://github.com/rapid7/metasploit-framework", description: "Penetration testing framework" },
    { name: "Nmap", url: "https://github.com/nmap/nmap", description: "Network exploration and security auditing" },
    { name: "Burp Suite", url: "https://github.com/PortSwigger", description: "Web vulnerability scanner" },
    { name: "Wireshark", url: "https://github.com/wireshark/wireshark", description: "Network protocol analyzer" },
    { name: "John the Ripper", url: "https://github.com/openwall/john", description: "Password cracker" },
    { name: "Snort", url: "https://github.com/snort3/snort3", description: "Network intrusion detection system" },
    { name: "Aircrack-ng", url: "https://github.com/aircrack-ng/aircrack-ng", description: "Wi-Fi security auditing tool" },
    { name: "OpenVAS", url: "https://github.com/greenbone/openvas", description: "Vulnerability assessment system" },
    { name: "Hydra", url: "https://github.com/vanhauser-thc/thc-hydra", description: "Network login cracker" },
  ],
  youtubeLinks: [
    { title: "OWASP ZAP Tutorial", url: "https://www.youtube.com/watch?v=example1" },
    { title: "Metasploit Basics", url: "https://www.youtube.com/watch?v=example2" },
    { title: "Nmap for Beginners", url: "https://www.youtube.com/watch?v=example3" },
    { title: "Burp Suite Crash Course", url: "https://www.youtube.com/watch?v=example4" },
    { title: "Wireshark Tutorial", url: "https://www.youtube.com/watch?v=Ke90Tje7VS0" },
    { title: "John the Ripper Guide", url: "https://www.youtube.com/watch?v=4D9q8Y3l0Oo" },
    { title: "Snort Intrusion Detection", url: "https://www.youtube.com/watch?v=Wy9q22isx3U" },
    { title: "Aircrack-ng Wi-Fi Hacking", url: "https://www.youtube.com/watch?v=example19" },
    { title: "OpenVAS Setup", url: "https://www.youtube.com/watch?v=example20" },
    { title: "Hydra Password Cracking", url: "https://www.youtube.com/watch?v=example21" },
  ],
  mediumLinks: [
    { title: "Cybersecurity Basics", url: "https://medium.com/@example/cybersecurity-basics-345" },
    { title: "Metasploit for Penetration Testing", url: "https://medium.com/@example/metasploit-testing-678" },
    { title: "Nmap Security Tips", url: "https://medium.com/@example/nmap-tips-901" },
    { title: "Burp Suite Guide", url: "https://medium.com/@example/burp-suite-234" },
    { title: "Wireshark Network Analysis", url: "https://medium.com/@example/wireshark-analysis-567" },
    { title: "John the Ripper Techniques", url: "https://medium.com/@example/john-techniques-890" },
    { title: "Snort Configuration Guide", url: "https://medium.com/@example/snort-guide-123" },
    { title: "Aircrack-ng for Wi-Fi", url: "https://medium.com/@example/aircrack-ng-456" },
    { title: "OpenVAS Best Practices", url: "https://medium.com/@example/openvas-practices-789" },
    { title: "Hydra Usage Tips", url: "https://medium.com/@example/hydra-tips-101" },
  ],
};