export const dataScience = {
  gitHubLinks: [
    { name: "Pandas", url: "https://github.com/pandas-dev/pandas", description: "Data manipulation and analysis" },
    { name: "NumPy", url: "https://github.com/numpy/numpy", description: "Fundamental package for scientific computing" },
    { name: "Matplotlib", url: "https://github.com/matplotlib/matplotlib", description: "Plotting library for Python" },
    { name: "Jupyter", url: "https://github.com/jupyter/notebook", description: "Interactive computing environment" },
    { name: "Seaborn", url: "https://github.com/mwaskom/seaborn", description: "Statistical data visualization" },
    { name: "Statsmodels", url: "https://github.com/statsmodels/statsmodels", description: "Statistical modeling and econometrics" },
    { name: "Dask", url: "https://github.com/dask/dask", description: "Parallel computing with Pandas-like API" },
    { name: "Plotly", url: "https://github.com/plotly/plotly.py", description: "Interactive plotting library" },
    { name: "SciPy", url: "https://github.com/scipy/scipy", description: "Scientific computing tools" },
    { name: "TensorFlow Datasets", url: "https://github.com/tensorflow/datasets", description: "ML dataset library" },
  ],
  youtubeLinks: [
    { title: "Pandas Tutorial", url: "https://www.youtube.com/watch?v=example9" },
    { title: "NumPy Crash Course", url: "https://www.youtube.com/watch?v=example10" },
    { title: "Matplotlib Basics", url: "https://www.youtube.com/watch?v=example11" },
    { title: "Jupyter Notebook Guide", url: "https://www.youtube.com/watch?v=example12" },
    { title: "Seaborn Visualization", url: "https://www.youtube.com/watch?v=Ke90Tje7VS0" },
    { title: "Statsmodels Tutorial", url: "https://www.youtube.com/watch?v=4D9q8Y3l0Oo" },
    { title: "Dask for Big Data", url: "https://www.youtube.com/watch?v=Wy9q22isx3U" },
    { title: "Plotly Interactive Charts", url: "https://www.youtube.com/watch?v=example25" },
    { title: "SciPy for Science", url: "https://www.youtube.com/watch?v=example26" },
    { title: "TensorFlow Datasets Intro", url: "https://www.youtube.com/watch?v=example27" },
  ],
  mediumLinks: [
    { title: "Pandas for Data Analysis", url: "https://medium.com/@example/pandas-analysis-789" },
    { title: "NumPy Essentials", url: "https://medium.com/@example/numpy-essentials-012" },
    { title: "Matplotlib Visualization Tips", url: "https://medium.com/@example/matplotlib-tips-345" },
    { title: "Jupyter for Data Science", url: "https://medium.com/@example/jupyter-data-science-678" },
    { title: "Seaborn Data Visualization", url: "https://medium.com/@example/seaborn-visualization-901" },
    { title: "Statsmodels for Statistics", url: "https://medium.com/@example/statsmodels-guide-234" },
    { title: "Dask for Scalable Data", url: "https://medium.com/@example/dask-scalable-567" },
    { title: "Plotly for Dashboards", url: "https://medium.com/@example/plotly-dashboards-890" },
    { title: "SciPy Advanced Topics", url: "https://medium.com/@example/scipy-topics-123" },
    { title: "TensorFlow Datasets Usage", url: "https://medium.com/@example/tensorflow-datasets-456" },
  ],
};