export const iot = {
  gitHubLinks: [
    { name: "Arduino", url: "https://github.com/arduino/Arduino", description: "Open-source electronics platform" },
    { name: "Raspberry Pi", url: "https://github.com/raspberrypi", description: "Raspberry Pi tools and software" },
    { name: "ESP8266", url: "https://github.com/espressif/ESP8266_NONOS_SDK", description: "Wi-Fi module SDK" },
    { name: "ThingSpeak", url: "https://github.com/thingspeak", description: "IoT analytics platform" },
    { name: "Node-RED", url: "https://github.com/node-red/node-red", description: "Flow-based programming for IoT" },
    { name: "Blynk", url: "https://github.com/blynkkk/blynk-library", description: "IoT platform with mobile apps" },
    { name: "MQTT", url: "https://github.com/eclipse/paho.mqtt.javascript", description: "MQTT client library" },
    { name: "Tasmota", url: "https://github.com/arendst/Tasmota", description: "ESP-based IoT firmware" },
    { name: "Home Assistant", url: "https://github.com/home-assistant/core", description: "Open-source home automation" },
    { name: "Zigbee2MQTT", url: "https://github.com/Koenkk/zigbee2mqtt", description: "Zigbee to MQTT bridge" },
  ],
  youtubeLinks: [
    { title: "Arduino Tutorial", url: "https://www.youtube.com/watch?v=example5" },
    { title: "Raspberry Pi Basics", url: "https://www.youtube.com/watch?v=example6" },
    { title: "ESP8266 IoT Projects", url: "https://www.youtube.com/watch?v=example7" },
    { title: "ThingSpeak Tutorial", url: "https://www.youtube.com/watch?v=example8" },
    { title: "Node-RED for IoT", url: "https://www.youtube.com/watch?v=Ke90Tje7VS0" },
    { title: "Blynk IoT Setup", url: "https://www.youtube.com/watch?v=4D9q8Y3l0Oo" },
    { title: "MQTT Protocol Guide", url: "https://www.youtube.com/watch?v=Wy9q22isx3U" },
    { title: "Tasmota Firmware Setup", url: "https://www.youtube.com/watch?v=example22" },
    { title: "Home Assistant Guide", url: "https://www.youtube.com/watch?v=example23" },
    { title: "Zigbee2MQTT Tutorial", url: "https://www.youtube.com/watch?v=example24" },
  ],
  mediumLinks: [
    { title: "Getting Started with Arduino", url: "https://medium.com/@example/arduino-start-567" },
    { title: "Raspberry Pi IoT Projects", url: "https://medium.com/@example/raspberry-pi-iot-890" },
    { title: "ESP8266 for IoT", url: "https://medium.com/@example/esp8266-iot-123" },
    { title: "ThingSpeak Analytics", url: "https://medium.com/@example/thingspeak-analytics-456" },
    { title: "Node-RED Flow Basics", url: "https://medium.com/@example/node-red-basics-789" },
    { title: "Blynk IoT Development", url: "https://medium.com/@example/blynk-development-101" },
    { title: "MQTT for IoT Communication", url: "https://medium.com/@example/mqtt-iot-234" },
    { title: "Tasmota IoT Customization", url: "https://medium.com/@example/tasmota-custom-567" },
    { title: "Home Assistant Setup", url: "https://medium.com/@example/home-assistant-890" },
    { title: "Zigbee2MQTT Integration", url: "https://medium.com/@example/zigbee2mqtt-123" },
  ],
};