export const machineLearning = {
  gitHubLinks: [
    { name: "TensorFlow", url: "https://github.com/tensorflow/tensorflow", description: "An open-source machine learning framework" },
    { name: "PyTorch", url: "https://github.com/pytorch/pytorch", description: "A deep learning framework" },
    { name: "Scikit-learn", url: "https://github.com/scikit-learn/scikit-learn", description: "Machine learning in Python" },
    { name: "Keras", url: "https://github.com/keras-team/keras", description: "Deep learning API" },
    { name: "XGBoost", url: "https://github.com/dmlc/xgboost", description: "Optimized gradient boosting library" },
    { name: "LightGBM", url: "https://github.com/microsoft/LightGBM", description: "Gradient boosting framework" },
    { name: "MLflow", url: "https://github.com/mlflow/mlflow", description: "Machine learning lifecycle platform" },
    { name: "CatBoost", url: "https://github.com/catboost/catboost", description: "Gradient boosting library" },
    { name: "H2O.ai", url: "https://github.com/h2oai/h2o-3", description: "Open-source ML platform" },
    { name: "FastAI", url: "https://github.com/fastai/fastai", description: "High-level deep learning library" },
  ],
  youtubeLinks: [
    { title: "TensorFlow Tutorial for Beginners", url: "https://www.youtube.com/watch?v=tpCFfeUEG2A" },
    { title: "PyTorch Crash Course", url: "https://www.youtube.com/watch?v=GIsg-ZUy0MY" },
    { title: "Machine Learning with Scikit-learn", url: "https://www.youtube.com/watch?v=hnQ-2haEomk" },
    { title: "Keras Basics", url: "https://www.youtube.com/watch?v=1L4L9fG7OEg" },
    { title: "XGBoost Tutorial", url: "https://www.youtube.com/watch?v=OtD8w0F_KI8" },
    { title: "LightGBM Introduction", url: "https://www.youtube.com/watch?v=2W0-QwlvP14" },
    { title: "MLflow for ML Pipelines", url: "https://www.youtube.com/watch?v=pl3m-vN6kCg" },
    { title: "CatBoost Guide", url: "https://www.youtube.com/watch?v=example16" },
    { title: "H2O.ai Tutorial", url: "https://www.youtube.com/watch?v=example17" },
    { title: "FastAI Deep Learning", url: "https://www.youtube.com/watch?v=example18" },
  ],
  mediumLinks: [
    { title: "Introduction to TensorFlow", url: "https://medium.com/@example/intro-tensorflow-234" },
    { title: "PyTorch for Deep Learning", url: "https://medium.com/@example/pytorch-deep-learning-567" },
    { title: "Scikit-learn Tips and Tricks", url: "https://medium.com/@example/scikit-learn-tips-890" },
    { title: "Keras vs TensorFlow", url: "https://medium.com/@example/keras-vs-tensorflow-123" },
    { title: "XGBoost for Machine Learning", url: "https://medium.com/@example/xgboost-ml-456" },
    { title: "LightGBM Optimization", url: "https://medium.com/@example/lightgbm-optimization-789" },
    { title: "MLflow Best Practices", url: "https://medium.com/@example/mlflow-practices-101" },
    { title: "CatBoost Advanced Usage", url: "https://medium.com/@example/catboost-usage-234" },
    { title: "H2O.ai for ML", url: "https://medium.com/@example/h2o-ai-ml-567" },
    { title: "FastAI for Beginners", url: "https://medium.com/@example/fastai-beginners-890" },
  ],
};