export const webDevelopment = {
  gitHubLinks: [
    { name: "Svelte", url: "https://github.com/sveltejs/svelte", description: "Web development for the rest of us" },
    { name: "React", url: "https://github.com/facebook/react", description: "A JavaScript library for building user interfaces" },
    { name: "Vue.js", url: "https://github.com/vuejs/vue", description: "The Progressive JavaScript Framework" },
    { name: "Tailwind CSS", url: "https://github.com/tailwindlabs/tailwindcss", description: "A utility-first CSS framework" },
    { name: "Node.js", url: "https://github.com/nodejs/node", description: "JavaScript runtime for server-side development" },
    { name: "Express.js", url: "https://github.com/expressjs/express", description: "Fast, unopinionated web framework for Node.js" },
    { name: "Bootstrap", url: "https://github.com/twbs/bootstrap", description: "Open-source CSS framework" },
    { name: "Gatsby", url: "https://github.com/gatsbyjs/gatsby", description: "React-based framework for building websites" },
    { name: "TypeScript", url: "https://github.com/microsoft/TypeScript", description: "Typed superset of JavaScript" },
    { name: "Webpack", url: "https://github.com/webpack/webpack", description: "Module bundler for JavaScript" },
  ],
  youtubeLinks: [
    { title: "React Tutorial for Beginners", url: "https://www.youtube.com/watch?v=Ke90Tje7VS0" },
    { title: "Svelte Crash Course", url: "https://www.youtube.com/watch?v=4D9q8Y3l0Oo" },
    { title: "Vue.js Basics", url: "https://www.youtube.com/watch?v=Wy9q22isx3U" },
    { title: "Tailwind CSS Tutorial", url: "https://www.youtube.com/watch?v=mr15Xzb1Ook" },
    { title: "Node.js Full Course", url: "https://www.youtube.com/watch?v=TlB_eWDSMt4" },
    { title: "Express.js Tutorial", url: "https://www.youtube.com/watch?v=L72fhGm1tfE" },
    { title: "Bootstrap 5 Crash Course", url: "https://www.youtube.com/watch?v=4sosXZsdy-s" },
    { title: "Gatsby.js Tutorial", url: "https://www.youtube.com/watch?v=example13" },
    { title: "TypeScript for Beginners", url: "https://www.youtube.com/watch?v=example14" },
    { title: "Webpack Basics", url: "https://www.youtube.com/watch?v=example15" },
  ],
  mediumLinks: [
    { title: "Top Frontend Frameworks in 2025", url: "https://medium.com/@example/top-frontend-frameworks-2025-123" },
    { title: "Mastering React Hooks", url: "https://medium.com/@example/mastering-react-hooks-456" },
    { title: "Svelte vs React: A Comparison", url: "https://medium.com/@example/svelte-vs-react-789" },
    { title: "Building Responsive UIs with Tailwind", url: "https://medium.com/@example/tailwind-responsive-101" },
    { title: "Node.js Best Practices", url: "https://medium.com/@example/node-js-best-practices-234" },
    { title: "Express.js Middleware Guide", url: "https://medium.com/@example/express-middleware-567" },
    { title: "Bootstrap Customization Tips", url: "https://medium.com/@example/bootstrap-tips-890" },
    { title: "Gatsby for Static Sites", url: "https://medium.com/@example/gatsby-static-sites-123" },
    { title: "TypeScript Type Safety", url: "https://medium.com/@example/typescript-safety-456" },
    { title: "Webpack Optimization", url: "https://medium.com/@example/webpack-optimization-789" },
  ],
};